# Generated by Django 4.1 on 2024-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0011_alter_reference_reference_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='source',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
