# Generated by Django 4.1 on 2024-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0012_alter_reference_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='source',
            field=models.CharField(default='default.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
