# Generated by Django 4.1 on 2023-10-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('reference_title', models.CharField(max_length=200)),
                ('reference_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph_name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceFit.reference')),
            ],
        ),
    ]
