# Generated by Django 4.1 on 2023-12-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0003_alter_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_text',
            field=models.CharField(max_length=500),
        ),
    ]
