# Generated by Django 4.1 on 2023-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0004_alter_reference_reference_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='source',
            field=models.CharField(blank=True, choices=[], max_length=255),
        ),
        migrations.DeleteModel(
            name='Morph',
        ),
    ]
