# Generated by Django 4.1 on 2023-12-05 11:40

import FaceFit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0005_alter_reference_reference_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='source',
            field=models.ImageField(blank=True, null=True, upload_to=FaceFit.models.get_upload_to),
        ),
    ]
