# Generated by Django 4.1 on 2023-12-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0007_richtext_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richtext',
            name='parent',
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.DeleteModel(
            name='RichText',
        ),
    ]
