# Generated by Django 4.1 on 2023-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0009_alter_reference_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_title',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='source',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
