# Generated by Django 4.1 on 2023-12-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceFit', '0010_alter_reference_reference_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_title',
            field=models.CharField(max_length=255),
        ),
    ]
